name: another_buddy
description: Another Kernel Manager app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.6.5
  flutter_bloc: ^8.1.3
  root: ^2.0.4
  equatable: ^2.0.5
  reflectable: ^4.0.5
  dartx: ^1.1.0
  external_app_launcher: ^3.1.0
  shared_preferences: ^2.1.2
  kiwi: ^4.1.0
  flutter_local_notifications: ^15.0.1
  device_apps: ^2.2.0
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
